### PR TITLE
Add PHPCS support.

### PR DESCRIPTION
**Pull request by nickschuch**
We get fails with PHPCS and some warnings in Simpletest. But the Travis side of things is working.

Example: https://travis-ci.org/nickschuch/token/jobs/25302116

### CODE REVIEW

**Comment by penyaskito** [comment]
There are errors caused by the php version. Should we stick to 5.4?

**Comment by nickschuch** [comment]
Yep, I think we should stick with PHP 5.4. Im running the tests locally now to try and replicate. The goal from here is to get the tests green and well commit!

**Comment by Berdir** [comment]
Had a look at the .travis here, I think the version I added in https://github.com/larowlan/token/pull/18 covers all of this except the code sniffer part (and adding it to the README).

The code sniffer part is actually there as well but commented out because that was failing for search_api with weird errors.

It has a few improvements over this, it uses apache which seems to be more stable (I have no issues with 5.5) and it does a shallow git clone of core, which should be faster (--depth 1).

My suggestion would be to merge in the .travis in my pull request and then rebase this and try to get the code sniffer part working here and add it to the README.

**Comment by jibran** [comment]
Needs reroll to add phpcs tweak.

**Comment by jibran** [comment]
I have given it some thought and I think we can leave it for later so closing it for now.

**Pull request closed without merging**
