### PR TITLE
Make all comment testcases pass.

### PR DESCRIPTION
**Pull request by tienvx**

### CODE REVIEW

**Comment by jibran** [comment]
This needs reroll

**Comment by jibran** [comment]
@larowlan can you please have a look at the fix?

**Comment by larowlan** [comment]
Yeah, core is broken here, so we have to dance around it.

**Comment by larowlan** [comment]
comment.permalink is now entity.comment.canonical

**Comment by jibran** [comment]
The issue mentioned in https://github.com/larowlan/token/pull/8#issuecomment-51560160 is fixed so merging this.

**Pull request merged**
