### PR TITLE
Allow to run tests with travis-ci

### PR DESCRIPTION
**Pull request by Berdir**
See https://travis-ci.org/md-systems/token

Not all tests are passing yet, but not sure how to fix them, as comment url behavior changed in core, and while we can possibly just adapt the tests, I still think the core change is wrong ;)

### CODE REVIEW

**Comment by Berdir** [comment]
Oh, I forgot you already had it enabled :) Even better ;)

**Comment by Berdir** [comment]
Wrong button fail.

**Comment by Berdir** [comment]
Added another commit that fixed test fails in pathauto.module.

**Comment by Berdir** [comment]
Removed the coverage report option, that adds several minutes to the test run because I can't get it to limit itself to the module directory only, there are no unit tests anyway.

.travis file is based on https://github.com/nickveenhof/search-api-sandbox, btw.

**Comment by nickschuch** [comment]
Hey @Berdir, we have been working out of the following PR to add travis suppport https://github.com/larowlan/token/pull/3. Maybe we should consolidate?

**Comment by Berdir** [comment]
@nickschuch Oh, I didn't see that. How do we want to continue? I used the same script for our pathauto and redirect repositories, both are now green. That said, I don't care which version we use, it's only temporary until we can move the project back to d.o anyway. So if you want me do, I can update the pull request and remove .travis.yml.

**Pull request merged**
