### PR TITLE
Fix asset path error.

### PR DESCRIPTION
**Pull request by tienvx**

### CODE REVIEW

**Comment by penyaskito** [comment]
While we are at it, shouldn't we use a library?

**Comment by tienvx** [comment]
Do you mean we should use 'attach library' instead of 'attach js + css'?

**Comment by jibran** [comment]
This has been fixed in HEAD. Can you please update the PR to fix https://github.com/larowlan/token/blob/8.x-1.x/token.pages.inc#L20 and
https://github.com/larowlan/token/blob/8.x-1.x/token.pages.inc#L21?

**Comment by tienvx** [comment]
Fixed @jibran

**Comment by jibran** [comment]
Thank you for updating the PR.

**Pull request merged**
