### PR TITLE
Optimize field_tokens() by looping over requested tokens instead of all fields

### PR DESCRIPTION
**Pull request by Berdir**
field_tokens() is extremely slow right now because it accesses all fields. For some strange reason, it loops over all fields and checks if a token for them is requested.

It's much easier and faster to loop over tokens and check if they match a field on the entity.

Also removed some unused variables and double checks (like the token module check)

### CODE REVIEW

**Comment by Berdir** [comment]
Bump, rebased this, anyone wants to have a look at this? :)

This is a pretty serious performance issue right now, would be nice to have this fixed and cleaned up. I don't think anything bigger will happen soon in regards to field tokens...

**Comment by kimpepper** [comment]
This fail looks related:

```
[12-Jan-2015 15:20:54 UTC] PHP Fatal error:  Cannot access protected property Drupal\node\Entity\NodeType::$name in /home/travis/build/larowlan/drupal/modules/token/token.tokens.inc on line 465
```

**Comment by larowlan** [comment]
That went in today, use $type->label() instead

On 13 January 2015 at 10:58, Kim Pepper notifications@github.com wrote:

> This fail looks related:
> 
> [12-Jan-2015 15:20:54 UTC] PHP Fatal error:  Cannot access protected property Drupal\node\Entity\NodeType::$name in /home/travis/build/larowlan/drupal/modules/token/token.tokens.inc on line 465
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/token/pull/25#issuecomment-69677550.

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au

**Comment by Berdir** [comment]
Yeah, but it's not related to this pull request, this just touches field tokens , pretty sure that is in a separate function. 

Will probably look into the new fails in the next few days, but will open a separate pull request for that.

**Pull request merged**
