### PR TITLE
Convert README to markdown and show build status

### PR DESCRIPTION
**Pull request by kimpepper**

### CODE REVIEW

**Comment by larowlan** [comment]
We can do this, but we'd need to back it out for when development goes back to drupal.org. So not sure.

**Comment by kimpepper** [comment]
Why?

On 18 July 2014 13:42, Lee Rowlands notifications@github.com wrote:

> We can do this, but we'd need to back it out for when development goes
> back to drupal.org. So not sure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/larowlan/token/pull/19#issuecomment-49392651.

## 

Kim Pepper
Technical Director
PreviousNext

desk: 02 8005 8670
mobile: 0414 212 530
skype: kim.pepper

**Comment by jibran** [comment]
just fyi https://twitter.com/drupal_review/status/487541098789998592

**Comment by jibran** [comment]
I don't think this is a big deal so as the part of weekend clean up I am merging this. we can always revert this.
And I hope [Build Status](https://travis-ci.org/larowlan/token) sign will motivate us to fix the test.

**Pull request merged**
